# -*- coding: utf-8 -*-
"""Plastic-Waste-Detection-Using-YOLOv11-Semantic-Segmentation1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KjangDQ_LdBccDthGp9qWs6x-RiPVGn0
"""

from ultralytics import YOLO
from IPython.display import display, Image

!pip install roboflow

# Upload dataset
from roboflow import Roboflow
rf = Roboflow(api_key="je4gd5FBH1nd2JKOhMWK")
project = rf.workspace("freedomtech").project("plastic-trash-freedomtech")
version = project.version(1)
dataset = version.download("yolov11")

# Commented out IPython magic to ensure Python compatibility.
# %cd {home}

!yolo task=detect mode=train model=yolo11n-seg.pt data=/content/plastic-trash-freedomtech-1/data.yaml epochs=100 imgsz=640 plots=True

!pip install cvzone

import cv2
import numpy as np
from ultralytics import YOLO
import cvzone

model=YOLO('/content/runs/segment/train/weights/best.pt')

cap=cv2.VideoCapture('t2.mp4')

names=model.model.names

from google.colab.patches import cv2_imshow

while True:
    ret, frame = cap.read()
    if not ret:
        break

    frame = cv2.resize(frame, (1020, 500))

    results = model.track(frame, persist=True)

    if results[0].boxes is not None:
        boxes = results[0].boxes.xyxy.int().cpu().tolist()
        class_ids = results[0].boxes.cls.int().cpu().tolist()

        if results[0].boxes.id is not None:
            track_ids = results[0].boxes.id.int().cpu().tolist()
        else:
            track_ids = [-1] * len(boxes)

        masks = results[0].masks
        if masks is not None:
            clss = results[0].boxes.cls.cpu().tolist()
            masks = masks.xy
            overlay = frame.copy()

            for box, track_id, class_id, mask in zip(boxes, track_ids, class_ids, masks):

                c = names[class_id]

                x1, y1, x2, y2 = box


                if mask.size > 0:
                   mask = np.array(mask, dtype=np.int32).reshape((-1, 1, 2))

                   cv2.rectangle(frame, (x1, y1), (x2, y2), (0, 255, 0), 2)
                   cv2.fillPoly(overlay, [mask], color=(0, 0, 255))


                   cvzone.putTextRect(frame, f'{track_id}', (x2, y2), 1, 1)
                   cvzone.putTextRect(frame, f'{c}', (x1, y1), 1, 1)


            alpha = 0.5
            frame = cv2.addWeighted(overlay, alpha, frame, 1 - alpha, 0)

    cv2_imshow(frame)
    if cv2.waitKey(1) == 27:
        break

cap.release()
cv2.destroyAllWindows()

